---
name: "EPUB & MOBI files"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
jobs:
  build:
    name: "EPUB & MOBI"
    runs-on: "macos-latest"

    steps:
      - uses: actions/checkout@v2
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Paul Graham Essays"
          files: |
            *.epub
            *.mobi
            *.csv

      - name: Run
        run: |
          mkdir essays
          make all
